### ISSUE TITLE
Update download link

### ISSUE THREAD

**Issue by slacka** [marcosps/lo_useful#3]
The [TDF download link here](https://wiki.documentfoundation.org/Development/Linux_Build_Dependencies#lo_usefull_Shell_Script) points here: https://github.com/downloads/marcosps/lo_useful/pre-install.sh

Can we update it to a more recent version? Thanks!

**Comment by efegurkan** [comment]
I suggest using this https://github.com/blog/1547-release-your-software

**Comment by alexandrevicenzi** [comment]
@slacka, the file pointed on Wiki is the more recent one. Do you want support for new O.S versions?
@efegurkan, we are thinking about release versions, but for this we'll need a new repo.

**Comment by slacka** [comment]
@alexandrevicenzi 
I think you are mistaken. The most recent version includes all of the necessary dependencies for Ubuntu 14.10, while the one pointed to by the wiki does not. It also does not install ccache. That's a very old copy.

**Comment by alexandrevicenzi** [comment]
Oh, @slacka the file on Wiki is too old (7 Nov 2012).

We'll change link.

**Comment by alexandrevicenzi** [comment]
It's fixed, please take a look.
