### ISSUE TITLE
ccache needs a bigger cache to be useful

### ISSUE THREAD

**Issue by slacka** [marcosps/lo_useful#4]
If you're going to install the optional ccache by default, you should increase the size limit so it actually can increase the speed of future builds. I'd recommend:

```
ccache --max-size 10G
```

The default setting of 1 GB may actually hinder performance. Another option is to just not install it, as it [can cause build errors with clang.](https://wiki.documentfoundation.org/Development/Building_LibreOffice_with_Clang)

Thanks again for sharing this great script!

**Comment by marcosps** [comment]
@slacka sorry for not fixing this for 2 years...

It happened that I just noticed this bug today... :(

But now it is fixed!
